package kz.hxncus.mc.advancedapi.api.bukkit.recipe;

public enum RecipeType {
	ANVIL, BLASTING, BREWERY, CAMPFIRE, ENCHANT, FURNACE, GRINDSTONE, MERCHANT, SHAPED, SHAPELESS, SMELTING, SMOKING, STONECUTTING, SMITHING_TRIM, SMITHING_TRANSFORM
}
